colombia_autos_security:
    resource: "@ColombiaAutosSecurityBundle/Resources/config/routing.yml"
    prefix:   /

colombia_autosadministrador:
    resource: "@ColombiaAutosadministradorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
    pattern:   login_path
    defaults:  { _controller: ColombiaAutosSecurityBundle:Security:login }
login_check:
    pattern:   check_path
logout:
    path:   /logout