colombia_autosadministrador_organismo:
    resource: "@ColombiaAutosadministradorBundle/Resources/config/routing/organismo.yml"
    prefix:   /organismo

colombia_autosadministrador_carroceria:
    resource: "@ColombiaAutosadministradorBundle/Resources/config/routing/carroceria.yml"
    prefix:   /carroceria

colombia_autosadministrador_motor:
    resource: "@ColombiaAutosadministradorBundle/Resources/config/routing/motor.yml"
    prefix:   /motor

colombia_autosadministrador_color:
    resource: "@ColombiaAutosadministradorBundle/Resources/config/routing/color.yml"
    prefix:   /color

colombia_autosadministrador_marca:
    resource: "@ColombiaAutosadministradorBundle/Resources/config/routing/marca.yml"
    prefix:   /marca

colombia_autosadministrador_propietario:
    resource: "@ColombiaAutosadministradorBundle/Resources/config/routing/propietario.yml"
    prefix:   /propietario

colombia_autosadministrador_departamento:
    resource: "@ColombiaAutosadministradorBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento