ColombiaAutos\administradorBundle\Entity\Carroceria:
    type: entity
    table: carroceria
    id:
        codCarroceria:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            id: true
            column: cod_carroceria
            generator:
                strategy: NONE
    fields:
        tipoCarroceria:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: tipo_carroceria
    lifecycleCallbacks: {  }
    properties:
        codCarroceria:
            - NotBlank: ~
        tipoCarroceria:
            - NotBlank: ~