ColombiaAutos\administradorBundle\Entity\Ciudad:
    type: entity
    table: ciudad
    indexes:
        departamento_ciudad:
            columns:
                - cod_departamento
    id:
        codCiudad:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            id: true
            column: cod_ciudad
            generator:
                strategy: NONE
    fields:
        nombreCiudad:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: nombre_ciudad
    oneToOne:
        codDepartamento:
            targetEntity: Departamento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_departamento:
                    referencedColumnName: cod_departamento
            orphanRemoval: false
    lifecycleCallbacks: {  }
    properties:
        codCiudad:
            - NotBlank: ~
        nombreCiudad:
            - NotBlank: ~
        codDepartamento:
            - NotBlank: ~