ColombiaAutos\administradorBundle\Entity\Departamento:
    type: entity
    table: departamento
    id:
        codDepartamento:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            id: true
            column: cod_departamento
            generator:
                strategy: NONE
    fields:
        nombreDepartamento:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: nombre_departamento
    lifecycleCallbacks: {  }
    properties:
        codDepartamento:
            - NotBlank: ~
        nombreDepartamento:
            - NotBlank: ~
