ColombiaAutos\administradorBundle\Entity\Marca:
    type: entity
    table: marca
    id:
        codMarca:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            id: true
            column: cod_marca
            generator:
                strategy: NONE
    fields:
        nombreMarca:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: nombre_marca
    lifecycleCallbacks: {  }
