ColombiaAutos\administradorBundle\Entity\Propietario:
    type: entity
    table: propietario
    id:
        nroIdentificacion:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
            id: true
            column: nro_identificacion
            generator:
                strategy: NONE
    fields:
        nombresP:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: nombres_p
        apellidosP:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: apellidos_p
    manyToMany:
        nroLicencia:
            targetEntity: TarjetaDePropiedad
            cascade: {  }
            fetch: LAZY
            mappedBy: nroentificacion
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
