ColombiaAutosadministradorBundle\Entity\Ciudad:
Ciudad:
    type: entity
    table: ciudad
    indexes:
        departamento_ciudad:
            columns:
                - cod_departamento
    id:
        codCiudad:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            id: true
            column: cod_ciudad
    fields:
        nombreCiudad:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: nombre_ciudad
    manyToOne:
        departamento:
            targetEntity: Departamento
            inversedBy: ciudades
            joinColumns:
                name: cod_departamento
                referencedColumnName: cod_departamento
            orphanRemoval: false
    lifecycleCallbacks: {  }