ColombiaAutosadministradorBundle\Entity\Departamento:
Departamento:
    type: entity
    table: departamento
    id:
        codDepartamento:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            id: true
            column: cod_departamento
            generator:
                strategy: IDENTITY
    fields:
        nombreDepartamento:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: nombre_departamento
    oneToMany:
        ciudades:
            targetEntity: Ciudad
            mappedBy: Departamento
lifecycleCallbacks: {  }
